---
- hosts: ec2-centos
  gather_facts: false
  vars:
    - message: hello world
  tasks:
    - name: Install htop on centos
      yum: name="{{ item }}" state=present
      with_items:
       - htop
       - git
      when: ansible_os_family == 'RedHat'

    - name: try command keyword
      command: echo `hostnamectl` > /tmp/hello.log
      register: output
      #debug: msg="{{ item }}"
      #with_items: echo {{message}}  `date` by `hostname`

    - debug:
        var: output

