---
- hosts: ec2-centos
  become: yes
  tasks:
    - name: install software
      yum: name={{ item }}  state=present
      with_items:
        - git
        - htop
      when: ansible_os_family == 'RedHat'
    
    - name: try command keyword
      command: echo `hostnamectl` > /tmp/hello.log
      register: output
      #debug: msg="{{ item }}"
      #with_items: echo {{message}}  `date` by `hostname` 

    - debug:
        var: output

    - name: storage string in hello
      shell: echo {{message}}  `date` by `hostname` > /tmp/hello.log
      
